title: My Word Game
subtitle: Just like Scrabble©
description: >- # this means to ignore newlines until "baseurl:"
  This is the site for My Word Game landing page
author: R. Aubel
email: aubel.r@gmail.com
avatar: assets/images/avatar.png

baseurl: /mwg           # the subpath of your site, e.g. /blog
url: https://aubel-r.github.io  # the base hostname & protocol for your site